import AdminDrawer from "@/components/drawer/AdminDrawer";
import AdminNav from "@/components/nav/AdminNav";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import AuthProvider from "@/libs/AuthProvider";
import FlexBetween from "@/utils/FlexBetween";
import { redirect } from "next/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AdminLayout({ children }) {
  const session = await getServerSession(authOptions);
  if (session) {
    return (
      <html lang="en">
        <body className="h-screen w-full bg-[#fff]">
          <FlexBetween>
            <div className="w-full h-full  flex flex-col items-center">
              <AdminNav />
              <AuthProvider>{children}</AuthProvider>
            </div>
          </FlexBetween>
        </body>
      </html>
    );
  } else {
    redirect("/");
  }
}
