import type { Metadata } from "next";

import "./globals.css";
import AuthProvider from "@/libs/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full bg-[#F5F5F5]">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
